{% set version = "1.10.0" %}

package:
  name: six
  version: {{ version }}

source:
  fn: six-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/six/six-{{ version }}.tar.gz
  sha256: 105f8d68616f8248e24bf0e9372ef04d3cc10104f1980f54d57b2ce73a5ad56a

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - six

about:
  home: http://pypi.python.org/pypi/six/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python 2 and 3 compatibility utilities
  description: |
    Six provides simple utilities for wrapping over differences between
    Python 2 and Python 3. It is intended to support codebases that work on
    both Python 2 and 3 without modification. six consists of only one Python
    file, so it is painless to copy into a project.
  doc_url: http://pythonhosted.org/six/
  dev_url: https://bitbucket.org/gutworth/six

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
