travis:
  secure:
    BINSTAR_TOKEN: M5ObImr76t1S1cBHxjRb2fc4yQ/8PPWJwFM1ueS6JSQhVVSNzOyZBbjYhhJHrcqugcQNgIz/Bkf45fnH1a/kNq7DW1vRtyKwsB9PIbVI+IrchOP8QaoBRsHdSlnMXKt4alvXLMVYEM8r57zEMlYB6nud2ZG+IVpJTWpZHi/XJpqe6NKeycII+2CQvvK5lB8F5Jv0NRNxRTLNWGlXW+060Gu3l4lUpa+H4qkN6e/7z53KJoqrJNDlbL50rMSDtJYSmQw5cMllGqoLc+SqGRTlqJD9GxtSK5DVB8YiAwytH6zFtrbcM+SxHOx3gkGpCGnqLCykYsL4pHftTzria44/SGNPxRr79gYyuW+/3wUjRmVabMgXQbPxcN98P5PakkmO48zk+aVp3dCCUjYQw8mqGTsNZ5G9MBAniXjAPo55TR/SqIXjCRm0TdmLciry0khQe+koSX3H0kLvXrM9AfHXcJRsyGf0kTIXkyem0BR8xBHBPxppsX4xPi4QtZiNTjm8ESCe3DURLMDOg5Hlro0R9h8VCk1H85xeRFO1mc2Pjpv1VRDZrv7ZEwfPBQB+sGp/Tp+Mah6oErNVXBw60k1ZvgNYEucH0CDJWPj3GMraF1r0arsdrg+ayZF5h1XZOg0+X21nE/yRmZdImnBzCeFNMg7DbRZ/hi3Yj/ZmpWVFeJY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
